export * from './About';
export * from './Contact';
export * from './Login';
export * from './MainPage';
export * from './WrongPage';
export * from './OAuth2RedirectHandler';
export * from './Profile';
export * from './Register';
export * from './MailSuccess';
